services:
    dbi:
        env_file: ".env"
        build:
            context: .
            dockerfile: Dockerfile
        image: dbi
        volumes:
            - .:/app
        command:
            ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8080"]
        restart: unless-stopped
        working_dir: /app
        ports:
            - 8003:8080
